### ISSUE TITLE
Streamline the ROFT-handover demo using docker stack deploy

### ISSUE THREAD

**Issue by xEnVrE** [hsp-iit/roft-samples#1]
After a recent experience with external users that tried to run the ROFT handover demo, I decided to streamline the process required to run the demo on the `iCubGenova11` setup.

Specifically, I started testing `docker-compose` to automate the deployment of several containers - the one running the tracker and the control module and those running the machine learning parts. However, I discovered that with `docker-compose` it is not possible to run containers on different machines - if not resorting to `contexts` and different `yml` files.

Then I switched to `docker swarm` and `docker stack deploy` which allows defining a cluster of machines with exposed GPUs and with that, we can now deploy everything by using a single command:

```console
docker stack deploy -c docker-compose.yml roft-samples-handover-stack
```

It automatically opens a `yarpmanager` where I prepared a single Entity `ROFT_Handover_with_iCub (embedded)` where the user only needs to run all + connect all to be ready to start the demonstration. Meanwhile, the machine learning parts run headlessly on the other machine.

I have updated the `README.md` with instructions on how to repeat the setup of the swarm in the case of two machines, for future reference. Moreover, I added a more detailed [instructions set](https://github.com/hsp-iit/roft-samples/blob/master/assets/iCubGenova11_demo.md) for users of the `iCubGenova11` setup with all the steps required (including laptop names, cables to be connected, how to start the robot, etc..).

One drawback of this solution is that `docker stack deploy` - differently from `docker run` or `docker-compose`, does not support Linux `cgroups` nor the `--privileged` mode (more details in  https://github.com/moby/moby/issues/24862). Hence, the realsense node cannot be run from within the container as the permission to access the device are missing. Hence, I am resorting to run it outside of the containers, right after running the `yarprobotinterface`.

cc @pattacini @mfussi66 @gabrielecaddeo

**Comment by pattacini** [comment]
Lovely!

Just added a quick note via https://github.com/hsp-iit/roft-samples/pull/2.

**Comment by xEnVrE** [comment]
One problem that I realized this morning is that when setting up the `swarm` the worker machines will search for the `leader` machine every time the docker deamon starts, at boot time. If not reachable, maybe because the machine has been detached to be used as standalone machine, the docker daemon will refuse to start. Hence, docker will not be available to starts local containers.

This is quite annoying. I am searching for a solution, i.e. I am hoping the docker could start normally also if the swarm is not accessible. Anyone has experience with the same problem?

**Comment by pattacini** [comment]
>Anyone has experience with the same problem?

Maybe @valegagge?

**Comment by valegagge** [comment]
Hi @xEnVrE ,
maybe this is an obvious consideration, but anyway... did you exit from docker swarm mode when you finished your demo? so did you leave the workers and leader in a clean state?

**Comment by xEnVrE** [comment]
Thanks @valegagge. The tool is super new to me, so any consideration is helpful :) 

> did you exit from docker swarm mode when you finished your demo

do you mean that I should leave the sworm by issuing

```console
docker swarm leave
```
on the worker node?

Because this would require to join the swarm every time the demo is required. Or is there a less drastic way to change mode?

Thank you

**Comment by valegagge** [comment]
Hi @xEnVrE ,
> do you mean that I should leave the swarm by issuing `docker swarm leave`...

yes. it is necessary to avoid the problem you described before.
I don't know if exists a different solution... We created the swam and left it every time. for this, we adopted the solution of using scrips to perform these actions.

**Comment by xEnVrE** [comment]
Ok thanks, I will adopt this solution and update the documentation accordingly.

**Comment by xEnVrE** [comment]
Documentation updated.

Closing this for now as a satisfactory solution has been achieved. Thanks for all the tips and comments!
